### ISSUE TITLE
サービス構築量について（質問者：宮本）

### ISSUE THREAD

**Issue by n0bisuke** [n0bisuke/gs_dev9#2]
先ほどアップロードした、サービス概要をご覧いただきたいのですが、
自分でも大分ボリュームのある開発量という印象です。
のびすけさん観点で削った方が良い・修正した方が良いなど、
色々とお考えを伺わせてください。
お忙しいところ大変恐縮ですが、よろしくお願いいたします。

**Comment by n0bisuke** [comment]
シートを見た限り、GGAまでとGGA後で分けて実装を考えられているので問題ないと思います。
実装量については多すぎるという話でもないと思うので、宮本さん自身がどれくらいのスピードでやれるかだと思います！ 

強いて言えば、ログイン周りなどは必要ですがメインの機能では無いので、あまりにも時間がかかりそうならGGA時点では実装しなくても良いかもしれません。

**Comment by dmiyamoto** [comment]
承知しました。
ありがとうございました。
